version: '3.9'
services:
  typebot-db:
    image: postgres:16
    restart: always
    volumes:
      - ${PWD}/.typebot-build/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  typebot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: always
    ports:
      - '8080:9010'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env.docker
  typebot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: always
    ports:
      - '8081:9010'
    env_file: .env.docker
